# CONTAINER OS
FROM node:16.20.1-alpine
# CREATE APP DIRECTORY
WORKDIR /app
# COPY PACKAGE.JSON
COPY package*.json ./
# INSTALL NODE MODULES
RUN npm install
# COPY CONTENTS OF DIRECTORY TO CONTAINER
COPY . .
# EXPORT POSE
EXPOSE 7100
# CREATE ENTRYPOINT
ENTRYPOINT ["node", "app.js"]